Update cordova-plugin-file dependency
phonegap/phonegap-plugin-media-recorder pull request #17
Opened 2017-11-17 12:40 UTC by jcesarmobile

## Description
Update the cordova-plugin-file dependency and set engines accordingly 

## Related Issue
#16 

## Motivation and Context
cordova-plugin-file is outdated and uses old compat plugin which is integrated in cordova-android >= 6.3.0, update it to latest version

## How Has This Been Tested?
installed the plugin and ran tests

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-02-21 00:54 UTC, macdonst requested changes
Minor change because of new version of the file plugin.

2018-02-21 00:54 UTC, macdonst commented on plugin.xml
> +  <dependency id="cordova-plugin-file" version="^5.0.0"/>
Bump this to `^6.0.1`

2018-02-24 22:51 UTC, jcesarmobile commented
done

2018-02-28 03:17 UTC, macdonst approved these changes

2018-02-28 03:18 UTC, merged